type GlobalFormElement = HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement;
type GlobalOutputElement = HTMLElement | HTMLOutputElement;

interface SharedLinks {
	genera: Record<string, string>;
	resources: Record<string, any>;
	biomes: Record<string, string>;
	infestedBiomes: Record<string, boolean | string>;
	[key: string]: any;
}

interface SharedPageData {
	debug: boolean;
	name: string;
	oldName: string;
	pageType: string;
	portalglyphs: string;
	region: string;
	system: string;
	galaxy: string;
	civShort: string;
	civStub: string;
	civilized: string;
	discovered: string;
	discoveredlink: string;
	documented: string;
	documentedlink: string;
	builder: string;
	builderlink: string;
	docby: string;
	platform: string;
	discDate: string;
	docDate: string;
	version: string;
	moon: string | boolean;
	planet: string;
	moons: string[];
	axes: string;
	location: string;
	sentinel: string;
	description: string;
	summaryText: string;
	element_primary: string;
	element_secondary: string;
	type: string;
	subtype: string;
	class: string;
	inventory: string;
	economy: string;
	faction: string;
	wealth: string;
	pilot: string;
	galleryArray: string[];
	[key: string]: any;
}

interface SharedGlobalInputs {
	version: HTMLSelectElement;
	civ: HTMLInputElement | HTMLSelectElement;
	fileInput: HTMLInputElement;
	fileUpload: HTMLInputElement;
	portalglyphsInput: HTMLInputElement;
	galleryUpload: HTMLInputElement;
	discoveredInput: HTMLInputElement;
	discoveredlinkInput: HTMLInputElement;
	documentedInput: HTMLInputElement;
	documentedlinkInput: HTMLInputElement;
	docbyInput: HTMLInputElement;
	axesInput: HTMLInputElement;
	nameInput: HTMLInputElement;
	oldNameInput: HTMLInputElement;
	descriptionInput: HTMLInputElement | HTMLTextAreaElement;
	[key: string]: GlobalFormElement | HTMLElement | NodeListOf<Element> | ArrayLike<Element> | undefined;
}

interface SharedGlobalOutputs {
	output: HTMLElement;
	portalglyphButtons: HTMLElement;
	galleryItems: HTMLElement;
	galleryCode: HTMLElement;
	explanation: HTMLElement & { showModal?: () => void };
	fullArticle: HTMLElement;
	actions: HTMLElement;
	albumActions: HTMLElement;
	albumEntry: HTMLElement;
	albumOther: HTMLElement;
	footer: HTMLElement;
	location: HTMLElement;
	docby: HTMLElement;
	resourceList: HTMLElement;
	resourceBullets: HTMLElement;
	sentinelSentence: HTMLElement;
	usage: HTMLElement;
	summaryText: HTMLElement;
	oldName: HTMLElement;
	album: HTMLElement;
	addInfo: HTMLElement;
	acquirementGallery: HTMLElement;
	moonList: HTMLElement;
	sChance: HTMLElement;
	stats: HTMLElement;
	cost: HTMLElement;
	slots: HTMLElement;
	techslots: HTMLElement;
	contents: HTMLElement;
	regionLong: HTMLElement;
	expectedHubTag: HTMLElement;
	tradeTerminal: HTMLElement;
	planets: HTMLElement;
	explanationHeading: HTMLElement;
	explanationContent: HTMLElement;
	explanationImg: HTMLImageElement;
	explanationLink: HTMLAnchorElement;
	[key: string]: GlobalOutputElement | undefined;
}

interface SharedGlobalElements {
	input: SharedGlobalInputs;
	output: SharedGlobalOutputs;
	[section: string]: Record<string, any>;
}

declare var links: SharedLinks;
declare var pageData: SharedPageData;
declare var globalElements: SharedGlobalElements;
declare var regions: Record<string, Record<string, string>>;
declare var uploadShown: boolean;
declare var dataIntegrityObj: { text: string; copy: boolean };
declare var galleryUploadShown: boolean;
declare var startupFunctions: (() => void) | undefined;

declare function addStaticPageData(key: string, value: unknown): void;
declare function enableTextMarking(): void;
declare function showAll(): void;
declare function copyCode(element: HTMLElement, targetId: string): void;
declare function errorMessage(element: Element, msg?: string | null): void;
declare function checkDataIntegrity(simple?: boolean): false | string;
declare function resolveBoundElements(dest: string): unknown;
declare function wikiCode(value: unknown, dest?: string): void;
declare function updateGlobalElements(object: Record<string, Record<string, any>>): void;
declare function sanitiseString(input: string): string;
declare function setDropdownOptions(element: HTMLSelectElement, values: string[], texts?: string[]): void;
declare function getChildIndex(array: ArrayLike<Element>, data: string): number;
declare function explanation(heading: string, text: string, img?: string): void;
declare function assignElementFunctions(object: Record<string, any>): void;
declare function assignFunction(element: Element, functionName: string, listener?: string | null, invert?: boolean): void;
declare function assignLink(element: HTMLElement, link: string): void;
declare function hideOrgName(): void;
declare function hideInput(element: Element, displayValue?: string | null): void;
declare function locationSentence(): void;
declare function formatName(documenter: string): string;
declare function numberError(element: HTMLInputElement, value?: string, decimals?: number | null, outputRaw?: boolean): string;
declare function getDescriptorData(): Record<string, Record<string, string[]>>;
declare function getCreatureData(): any;
declare function getResourceData(): Record<string, string>;
declare function getSentinelData(): Record<string, string[]>;
declare function enPrefix(text: string, dest?: string | null): string;
declare function addInfoBullet(): void;
declare function albumName(): void;
declare function albumDiscoverer(): void;
declare function albumItemType(): void;
declare function albumOther(): void;
declare function albumDesc(): void;
declare function planetMoonSentence(planet?: string, moon?: string): string | void;
declare function docByExternal(): void;
declare function hideDiscoverer(keepId?: string | null, removeId?: string | null): void;
declare function docBy(): void;
declare function albumDropdown(): void;
declare function pageName(): string;
declare function bundlePropFunctions(): void;
declare function hideAlbumEntry(): void;
declare function albumFunctions(): void;
declare function noLineBreak(): void;
declare function regexMatch(string: string, regex: RegExp): boolean;
declare function checkboxWikiCode(element: HTMLInputElement): void;
declare function removeSection(array: ArrayLike<Element>): void;
declare function removeSpecificSection(sectionName: string, attribute?: string): void;
declare function image(element: HTMLInputElement): void;
declare function plural(number: number, dest?: string | null): string | void;
declare function datalists(object: Record<string, string[]>): void;
declare function getCurrentYear(outputId: string): void;
declare function storeData(element: HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement): void;
declare function extractNumber(value: string): string;
declare function numberStats(element: HTMLInputElement, decimals?: number | null, outputRaw?: boolean): string;
declare function shortenGHub(civ: string): string;
declare function validateCoords(error?: boolean): boolean;
declare function regNr(regionName: string): string;
declare function HubGal(civ: string): string | undefined;
declare function planetMoon(moon?: string): string;
declare function getHubNumber(regionName: string): string | number | undefined;
declare function toggleSection(sectionName?: string, button?: HTMLElement, attributeName?: string): void;
declare function oddEven(number: number): string;
declare function assignDefaultValue(element: HTMLInputElement, value?: string): void;
declare function forceDatalist(element: HTMLInputElement | HTMLSelectElement): void;
declare function wikiCodeSimple(element: HTMLInputElement): void;
declare function sortObj<T>(obj: T, number?: boolean): T;
declare function addAllTooltips(): void;
declare function buildDescriptor(descriptor: string, planetClass: string, filler: string): string;
declare function autoInfested(element?: HTMLInputElement): boolean | void;
declare function celestialStartupFunctions(): void;
declare function wikiCodePercentage(element?: HTMLInputElement | null): void;
declare function galleryUpload(): void;
declare function glyphInputOnChange(input?: HTMLInputElement | null): void;
declare function glyphRegion(glyphs: string): void;

declare function resetGallery(): void;
declare function resetExternal(): void;
declare const Sortable: any;
